### ISSUE TITLE
Add nagios monitoring of automated processes

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#40] opened 2016-06-06 22:33 UTC
_From @mejackreed on March 29, 2016 18:14_

_Copied from original issue: sul-dlss/sul-pub#161_

**Comment by mejackreed** [comment] 2016-06-06 22:33
_From @darrenleeweber on March 29, 2016 20:53_

Moving comment from #107 here.
@tallenaz says, "We're currently monitoring two harvesting logs: one associated with the nightly harvest, and the other for the fortnightly harvest -- we check to see how long it has been since the log has last been written to, and if it has been longer than a certain threshold, nagios will alert."

Q. for @tallenaz -- can we monitor any of the log content with a grep for `ERROR`?  In the case of the cap authors poller, the logs were written regularly, but they were full of errors.

**Comment by mejackreed** [comment] 2016-06-06 22:33
_From @drh-stanford on April 4, 2016 19:0_

There already is an `is_it_working` gem that's configured to test the database and CAP connectivity. But we'd likely need to add harvesting and API-level verification.

https://github.com/sul-dlss/sul-pub/blob/master/config/initializers/is_it_working.rb

**Comment by mejackreed** [comment] 2016-06-06 22:33
_From @drh-stanford on April 8, 2016 20:9_

I've added PR #215 to improve the `is_it_working` endpoint for monitoring

**Comment by mejackreed** [comment] 2016-06-06 22:33
_From @bess on April 14, 2016 19:18_

Alerts should go to sulpub-low@sul-dlss.pagerduty.com

**Comment by mejackreed** [comment] 2016-06-06 22:33
_From @tallenaz on May 25, 2016 22:41_

I've set up the nagios checks to monitor the nightly and fortnightly harvest logs. Currently, notifications for those checks are off, as the fortnightly harvest log won't exist to monitor until the next time the harvest kicks off, and the nightly harvest is intentionally off for now.

**Comment by drh-stanford** [comment] 2016-10-21 19:29
duplicate of #119

**Closed by drh-stanford** 2016-10-21 19:29 UTC
Labels: devops, in progress, technical debt
